---
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - stack.env
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3001:3000
    volumes:
      - /home/administrador/portainer/homepage/config:/app/config
      - /home/administrador/portainer/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
